@startuml
!include http://host.docker.internal:8000/data_lib.puml

title "Collections Example - Data"
footer Last Updated: 8/11/2022

Collection( organizations ) {
  PrimaryKey( _id, objectId )
  Field( name, string )
  ForeignKey( team_ids, array[teams._id] )
  Field( created_at, timestamp )
  Field( updated_at, timestamp )
}

Collection( teams ) {
  PrimaryKey( _id, objectId )
  ForeignKey( organization_id, organizations._id )
  Field( name, string )
  ForeignKey( user_ids, array[users._id] )
  Field( created_at, timestamp )
  Field( updated_at, timestamp )
}

Collection( users ) {
  PrimaryKey( _id, objectId )
  ForeignKey( organization_id, organizations._id )
  Field( first_name, string )
  Field( last_name, string )
  Field( email, string )
  Field( password, string )
  Field( created_at, timestamp )
  Field( updated_at, timestamp )
}

organizations::team_ids -> teams::_id
teams::organization_id -> organizations::_id
teams::user_ids -> users::_id
users::organization_id -> organizations::_id

@enduml
