@startuml constants-lib

!$version = "v1.0.0"
!$last_updated = "6/16/2022"

' CHANGELOG
' v1.0.0
' 6/16/2022
' Initial Release

' https://htmlcolorcodes.com
!$START_GREEN = "#00FF00"
!$RED = "#E6B0AA"
!$ORANGE = "#F5CBA7"
!$YELLOW = "#F9E79F"
!$GREEN = "#ABEBC6"
!$BLUE = "#AED6F1 "
!$PURPLE = "#D7BDE2"

!$ABOVE = "top"
!$BELOW = "bottom"

!$UP = "top"
!$DOWN = "bottom"
!$LEFT = "left"
!$RIGHT = "right"

' DATA
!$LEGACY_TABLE = "#D34C45"
!$SCHEMA = "#66CCFF"
!$TABLE = "#ABEBC6"
!$VIEW = "#E3E07B"
!$COLUMN = "#BFC9CA"
!$NEW_COLUMN = "#1EA80F"
!$LEGACY_COLUMN = "#D34C45"
!$METHOD = "#BFC9CA"
!$FUNCTION = "#BFC9CA"
!$INDEX = "#BFC9CA"
!$NEW_INDEX = "#1EA80F"

'!$COLLECTION = "#ABEBC6"
!$COLLECTION = "#6dbd8f"
!$SUB_DOCUMENT = "#DEFFEC"
!$FIELD = "#BFC9CA"

!$PRIMARY_KEY = "#F8C471"
!$FOREIGN_KEY = "#95A5A6"
!$NEW_FOREIGN_KEY = "#1EA80F"
!$LEGACY_FOREIGN_KEY = "#D34C45"

@enduml
