@startuml data-lib

!include http://host.docker.internal:8000/constants_lib.puml

!$version = "v2.0.0"
!$last_updated = "8/30/2022"

' CHANGELOG
' v2.0.0
' 8/31/2022
' Rebuilt how data renders

' v1.0.0
' 8/11/2022


!procedure PrimaryKey($name, $type)
    {field}<color:$PRIMARY_KEY><&key></color> <b>$name</b> : $type
!endprocedure

!procedure ForeignKey($name, $type)
    {field}<color:$FOREIGN_KEY><&key></color> <b>$name</b> : $type
!endprocedure

' SQL
!procedure Table($name, desc="")
    class $name << (T, $TABLE) >>
!endprocedure

!procedure Column($name, $type)
    {field}<color:$COLUMN><&media-record></color> <b>$name</b> : $type
!endprocedure

!procedure Method($name, $type="")
    !if ($type == "")
        {method}<color:$METHOD><&caret-right></color> <b>$name()</b>
    !else
        {method}<color:$METHOD><&caret-right></color> <b>$name()</b> : $type
    !endif
!endprocedure

!procedure Function($name, $type="")
    !if ($type == "")
        {method}<color:$METHOD><&caret-right></color> <b>$name()</b>
    !else
        {method}<color:$METHOD><&caret-right></color> <b>$name()</b> : $type
    !endif
!endprocedure

' NoSQL
!procedure Collection($name)
    class $name << (T, $COLLECTION) >>
!endprocedure

!procedure Field($name, $type)
    {field}<color:$FIELD><&media-record></color> <b>$name</b> : $type
!endprocedure

@enduml
