@startuml data-lib

!$version = "v1.0.0"
!$last_updated = "8/11/2022"

' CHANGELOG
' v1.0.0
' 8/11/2022

!procedure PrimaryKeyIcon($name, $type)
    <color:#b8861b><&key></color> <b>$name</b> => $type
!endprocedure

!procedure PrimaryKey($name, $type)
    $name => $type
!endprocedure

!procedure ForeignKeyIcon($name, $type)
    <color:#aaaaaa><&key></color> <b>$name</b> => $type
!endprocedure

!procedure ForeignKey($name, $type)
    $name => $type
!endprocedure

' SQL
!procedure Table($name)
    map "<size:15><b>$name</b></size>" as $name
!endprocedure

!procedure Column($name, $type)
    <color:#efefef><&media-record></color> $name => $type
!endprocedure

' NoSQL
!procedure Collection($name)
    map "<size:15><b>$name</b></size>" as $name
!endprocedure

!procedure FieldIcon($name, $type)
    <color:#efefef><&media-record></color> $name => $type
!endprocedure

!procedure Field($name, $type)
    $name => $type
!endprocedure

@enduml
