@startuml flow-lib

!include http://host.docker.internal:6250/constants_lib.puml

!$version = "v1.0.1"
!$last_updated = "9/17/2022"

' scale .75

hide empty description

' CHANGELOG
' v1.0.1
' 9/17/2024
' Changed structure for better customization

' v1.0.0
' 6/16/2022
' Initial Release

!procedure Start($ID, $TXT, $COLOR=$START_GREEN)
  state "  **$TXT**  " as $ID $COLOR
!endprocedure

!procedure Question($ID, $TXT, $COLOR=$YELLOW)
  state "  $TXT  " as $ID $COLOR
!endprocedure

!procedure Answer($ID, $TXT, $COLOR=$GREEN)
  state "  $TXT  " as $ID $COLOR
!endprocedure

!procedure End($ID, $TXT, $COLOR=$RED)
  state "  $TXT  " as $ID $COLOR
!endprocedure

@enduml
