@startuml
!include http://host.docker.internal:8000/level_lib.puml

title api-gateway
header Overview
footer 8/11/2022 \n Library: $version \n PlantUML: %version()

Actor(User, "User")
Generic(ECS1, "ECS", "api-gateway")
Generic(ECS2, "ECS", "bi|flux|txm", "[ something ]")
Database(Database, "Database")

User -down-> ECS1
ECS1 -right-> Database
ECS1 -down-> ECS2

@enduml

@startuml
!include http://host.docker.internal:8000/data_lib.puml

title "hey"
header asdf
footer 02/18/2022 \nLibrary: version \nPlantUML: %version()



@enduml